### ISSUE TITLE
Difference from imagebind

### ISSUE THREAD

**Issue by lzw-lzw** [PKU-YuanGroup/LanguageBind#2]
Thank you for your excellent work. I want to know what is the difference between this work and ImageBind. According to my understanding, the difference is mainly reflected in the different modalities used as band, right? Thanks!

**Comment by openworld-lab** [comment]
Thank you for your question and you are referring to one of its highlights. To summarize, firstly, a language-binding approach is more suitable for the majority of language-based downstream tasks due to the absence of an intermediate modality. Secondly, LanguageBind is pre-trained on the VIDAL-10M dataset, where the direct alignment of video, infrared, depth, and language data pairs outperforms the indirect integration of image-based modality data. Additionally, within VIDAL-10M, the language modality is a multi-view textual description enhanced by advanced models like ChatGPT. This ensures that the central modality possesses sufficient semantic information to bind effectively with other modal data.

**Comment by lzw-lzw** [comment]
Got it, thanks for your patient reply!
